### ISSUE TITLE
Pathway Network subtab in DEG2 tab

### ISSUE THREAD

**Issue by gexijin** [gexijin/idepGolem#156]
**What**
Error  when deployed on dev server:
 Error in <Anonymous>: cannot open file 'Rplots.pdf'
**To reproduce**
Got to http://idepdev.jacks.local/idepgolem/,
This needs to be from campus network, or VPN.
Load demo data, click DEG1, submit and then DEG2, the last tab.

**Comment by espors** [comment]
@gexijin  Is this still an issue on the dev site? For http://149.165.154.220/idepgolem/ it is not.
