### ISSUE TITLE
Visualize genes 

### ISSUE THREAD

**Issue by JianYes** [gexijin/idepGolem#252]
Any possibility to visualize genes in PCA, Volcano, MA, and Scatter plots? Some users asked for it.

**Comment by bderenge** [comment]
The pca_tools biplot has a checkbox "show loadings" which displays the ~5 genes with the largest affect on the principal components. Do we want to add that to the default PCA plot?

**Comment by gexijin** [comment]
Problem is solved for volcano and MA plot. Only problem left is Scatter Plot in the DEG2 tab.
