### ISSUE TITLE
Diagnostic information is private

### ISSUE THREAD

**Issue by zw2913** [gexijin/idepGolem#434]
**Describe the bug**
Hi, this is a non-R related problem I have been experiencing. I use the website version of iDEP 1.0, and it has been fine for the past 3 days. Today I couldn't connect to the server and has this message every time "Please ask your system admin for permission if you need to check the R logs."

Thank you! 

**To Reproduce**
1. Go to http://149.165.154.220/idepg/
2. Click on "Browse" to upload count file. 
3. wait for data to upload 

**Expected behavior**
I expected to see the pre-processing page after uploading. 

**Screenshots**

**Additional context**
<img width="1207" alt="Screenshot 2022-11-16 at 15 48 39" src="https://user-images.githubusercontent.com/82825397/202290933-ca994bcb-1143-4ec6-83ab-d52abbae8a89.png">

**Comment by gexijin** [comment]
Thanks for submitting this issue. If you want us to reproduce the error, could you contact us via email gelabinfo@gmail.com? 
We need some example data, such as a small portion of your original data, to reproduce and trouble-shoot. 
Thanks.

**Comment by gexijin** [comment]
This is a general issue in iDEP. The users cannot access the error message. It is possible to catch the error and send to the user. See example below using the tryCatch function. This will be a lot of work to fix all functions.

```
  # stores the results after running the generated code.
  run_result <- reactive({
    req(openAI_response()$cmd)
      tryCatch(
        eval(parse(text = openAI_response()$cmd)),
        error = function(e) {
          print(paste("Error caught:", e$message))
          return(
            list(
              value = -1,
              message = capture.output(print(e$message))
            )
          )
        }
      )

  })

  output$result_plot <- renderPlot({
    req(openAI_response()$cmd)
    req(run_result())

    # if error, the returned list has two elements.
    if(length(run_result()) == 2) {
      grid::grid.newpage()
          grid::grid.text(
            paste(
              "Error: ",
              run_result()$message,
              "\nPlease try again by click Re-submit."
            ),
            x = 0.5,
            y = 0.85,
            gp = grid::gpar(
              col = "red",
              fontsize = 15
            )
          )
    } else {
      run_result() # show plot
    }

  })
```
