### ISSUE TITLE
Experimental Design Single Levels

### ISSUE THREAD

**Issue by treodeo** [gexijin/idepGolem#444]
**Describe the bug**
Experimental designs with only one level in a factor will break the session and require reloading the site.

**To Reproduce**
1. Upload the experimental design provided.
2. Upload feature counts provided
3. Go to Pre-Process
4. Breaks

**Expected behavior**
Ignore single level factors.

**files**
[ExperimentDesign_iDEP.bad.csv](https://github.com/gexijin/idepGolem/files/10504098/ExperimentDesign_iDEP.bad.csv)
[LT3LT36_featureCounts.subsampled_tbl.2.LT3.csv](https://github.com/gexijin/idepGolem/files/10504099/LT3LT36_featureCounts.subsampled_tbl.2.LT3.csv)

[](url)

**Comment by gexijin** [comment]
Thank you. I never thought people will put one level in a factor. I will fix that.

**Comment by treodeo** [comment]
True, this isn't immediately obvious. I ran into this error because I wanted to subset the data and forgot to remove that factor in the design table. 

Maybe, the real solution is to allow subsetting or filtering. It's not clear from the DEG1 panel that I can make comparison solely between 2 out of the 4 treatment groups in a 2x2 design. Hope that makes sense.
