### ISSUE TITLE
Add gitters to gene plot

### ISSUE THREAD

**Issue by gexijin** [gexijin/idepGolem#447]
**Is your feature request related to a problem? What value do you see this adding? Please describe.**
Add jitters to the bar plot on the Pre-Process tab, gene plot. 

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/18232433/223485539-6368ea52-e162-4e4c-89b4-1d035a4d394b.png)

**Comment by gexijin** [comment]
Add p-values and brackets. 
![image](https://user-images.githubusercontent.com/18232433/224104274-afa5a820-d89a-47bb-a21d-be9fd848686b.png)

**Comment by gexijin** [comment]
Thanks for the suggestion! We will take a look.

**Comment by ChrisTret** [comment]
Thank you very much for your input. A solution is underway.
