### ISSUE TITLE
Pathway Report Generation Fails

### ISSUE THREAD

**Issue by treodeo** [gexijin/idepGolem#452]
**Describe the bug**
After pathway analysis is completed. Generated reports do not download successfully.

**To Reproduce**
1. Upload the following datasets
[LT37_ExpDesign_iDEP.csv](https://github.com/gexijin/idepGolem/files/11105713/LT37_ExpDesign_iDEP.csv)

[FeatureCounts.HighCounts.txt](https://github.com/gexijin/idepGolem/files/11105716/FeatureCounts.HighCounts.txt)

2. Pre-process with settings
![image](https://user-images.githubusercontent.com/6070112/228675337-9df79138-f2ad-4dde-9ea9-2637ad2c6c59.png)
4. Model only Genotype_Drug. Method Deseq, fdr cutoff 0.01, fold-change 2
![image](https://user-images.githubusercontent.com/6070112/228675388-fa0c2173-05a4-4f4a-964f-19e9fb5e56c0.png)
6. Pathway analysis. See the following settings
![image](https://user-images.githubusercontent.com/6070112/228675101-2b73619d-5ddc-41e3-95f2-9f349fc41fb0.png)
7. Error 
![image](https://user-images.githubusercontent.com/6070112/228675133-efa2b2c3-226e-41af-8181-dc9098b486d7.png)

** Additional notes

It would be great if we could get this fixed so I can preserve the analysis pipeline along with graphs/tables.

Thank you!

**Comment by gexijin** [comment]
Thank you for reporting this. I was able to reproduce this. It seems that the second time you click on it, it is working. I will take a look.

**Comment by gexijin** [comment]
This is fixed on http://bioinformatics.sdstate.edu/idep11/ 
Please let me know if there is any more issues.
