### ISSUE TITLE
Gene Symbols on Volcano Plot

### ISSUE THREAD

**Issue by treodeo** [gexijin/idepGolem#479]
Hello,

Could we get gene symbols to be plotted as labels on the Volcano plot? 
![image](https://user-images.githubusercontent.com/6070112/236283536-65fa9520-821e-44fd-a72c-5af08b963778.png)

Better yet, It'd be great to get the interactive version of this plot (ggplot style).

Thank you!

**Comment by gexijin** [comment]
Lloyd, 
This is finally fixed. https://github.com/gexijin/idepGolem/pull/496
Thanks.

**Comment by treodeo** [comment]
Thank you so much for the update! 😄
