### ISSUE TITLE
Excel files as an input files

### ISSUE THREAD

**Issue by gexijin** [gexijin/idepGolem#480]
**Is your feature request related to a problem? What value do you see this adding? Please describe.**
Currently IDEP only accepts CSV and TXT files as input files. Some users want to upload Excel files. This will cause iDEP to freeze when users uploads large Excel files.

**Describe the solution you'd like**
Use an R package that can read Excel files to read user files. This is implemented in RTutor, I think.
At the minimum, if users upload an large Excel file, reject that file and give them a warning message.

**Additional context**
 This is implemented in RTutor, I think.

**Comment by EricTulowetzke** [comment]
@gexijin I see this in code in current idep

# Read expression file -----------
    if (
      substr(in_file_data,
      nchar(in_file_data) - 4,
      nchar(in_file_data)) == ".xlsx"
    ) {
      data <- readxl::read_excel(in_file_data)
      data <- data.frame(data)
      
So can this ticket be close or do we still need to add warning for large file?

**Comment by EricTulowetzke** [comment]
I figure out to
