### ISSUE TITLE
Pathway "Generate Report" Fails

### ISSUE THREAD

**Issue by treodeo** [gexijin/idepGolem#487]
**Describe the bug**
The "Generate Report" feature in the Pathway analysis fails. Only a document that says "Pathway-report.html" functions.

**To Reproduce**
[LT37_ExpDesign_iDEP.csv](https://github.com/gexijin/idepGolem/files/11790004/LT37_ExpDesign_iDEP.csv)

1. Upload the following documents:
[LT37_LT37a_FeatureCounts.HighCounts.txt](https://github.com/gexijin/idepGolem/files/11790006/LT37_LT37a_FeatureCounts.HighCounts.txt)
2. Go to DEG1: Select Drug factor. Select DrugROT vs DrugSHAM. Submit for analysis.
3. Go to Pathway: Let it calculate. Click Generate report.
4. Download fails: pathway-report.html Failed - Server problem.

**Screenshots**
<img width="241" alt="image" src="https://github.com/gexijin/idepGolem/assets/6070112/a447c065-2dc7-445f-b426-338f19162cc1">

Using Google Chrome.

Thank you!

**Comment by gexijin** [comment]
Hi Lloyd, This is fixed. We forgot to name the package name when calling a function:
```
  **idepGolem::**enrichment_tree_plot(
    go_table = pathway_list_data,
    group = "All Groups" # ,
    # right_margin = 45
  )
```

**Comment by treodeo** [comment]
Thank you!
