### ISSUE TITLE
color for network in pathway are confused

### ISSUE THREAD

**Issue by JianYes** [gexijin/idepGolem#524]
**Describe the bug**
![image](https://github.com/gexijin/idepGolem/assets/42040574/2d2de45b-0826-475f-b79c-b10684702709)

**To Reproduce**
1. Go to 'idep1.1'
2. Click on 'Load Demo' which will upload demo data: 2 groups; Human
3. Go to DEG1 tab
4. Submit the design
5. Click Pathway
6. Click Network in the Pathway tab, we will see the note: Two pathways (nodes) are connected if they share 30% (default, adjustable) or more genes. Green and red represents down- and up-regulated pathways. But according to the "Significant pathways" in the same Pathway tab, the green pathways are up, and the red pathways are down. 

**Expected behavior**
Change the color green for down and red for up in the network plot, or change the note as: Green and red represents up- and down-regulated pathways.

**Screenshots**
![image](https://github.com/gexijin/idepGolem/assets/42040574/8524b8de-93f5-42e1-aae6-a61e6091a9b5)
![image](https://github.com/gexijin/idepGolem/assets/42040574/6ce22986-b891-4f81-9f26-69b0dabd3fe3)

**Additional context**

**Comment by gexijin** [comment]
Fixed
