### ISSUE TITLE
Add sample names for the heatmaps

### ISSUE THREAD

**Issue by JianYes** [gexijin/idepGolem#528]
**Is your feature request related to a problem? What value do you see this adding? Please describe.**
The heatmaps themselves have no sample name though the sub-heatmaps show the sample names
**Describe the solution you'd like**
Add sample names for the original heatmaps in Clustering, DEG2, Pathway, Bicluster and Network.

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/gexijin/idepGolem/assets/42040574/a0700108-5712-4e68-85a7-99a79172659a)

**Comment by ChrisTret** [comment]
Committed to my branch. Will pull when I push this afternoon.
