### ISSUE TITLE
Remove the information about PREDA

### ISSUE THREAD

**Issue by JianYes** [gexijin/idepGolem#529]
**Is your feature request related to a problem? What value do you see this adding? Please describe.**
We removed the PREDA subtabs in Genome tab, but the information about PREDA is still there.
**Describe the solution you'd like**
Remove the last sentence in Genome/Info subtab.

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/gexijin/idepGolem/assets/42040574/e0eab950-32ec-4ef8-aafc-80d6755afbad)

**Comment by gexijin** [comment]
I think this is fixed.

**Comment by gexijin** [comment]
I think this is fixed.
