### ISSUE TITLE
Add download options for Pathway/Significant pathway, Tree, Network, KEGG

### ISSUE THREAD

**Issue by JianYes** [gexijin/idepGolem#531]
**Is your feature request related to a problem? What value do you see this adding? Please describe.**
For tab Pathway, there is no download option for sub tab of Significant pathway, Tree, Network, and KEGG
**Describe the solution you'd like**
Can we add download options for sub tab of Significant pathway, Tree, Network, and KEGG in tab Pathway?
**Describe alternatives you've considered**

**Additional context**
For the Tree sub tab, the message of "Adjusting the width of the browser window can render figure differently and resolve the "Figure margin too wide" error on the bottom means nothing now.

**Comment by JianYes** [comment]
There is still no download option for Network in Pathway tab.

**Comment by gexijin** [comment]
The network plot has an export button at the the bottom of the page. That should suffice. Closing this issue. Thanks @ChrisTret
