### ISSUE TITLE
upload data and show data in original order

### ISSUE THREAD

**Issue by JianYes** [gexijin/idepGolem#533]
**Is your feature request related to a problem? What value do you see this adding? Please describe.**
The uploaded data file may be sorted according to the counts, so that it looks different from the csv or txt file.

**Describe the solution you'd like**
Can we keep the original order and make the uploaded data file look the same as the original one.

**Describe alternatives you've considered**

**Additional context**
Original data file and the screenshot it looks like in EXCEL:
[GSE100007.csv](https://github.com/gexijin/idepGolem/files/12442872/GSE100007.csv)
![image](https://github.com/gexijin/idepGolem/assets/42040574/356d5ec9-20a8-42ad-9f9a-a82d89e45161)
The screenshot it looks like in idep .96
![image](https://github.com/gexijin/idepGolem/assets/42040574/12fde162-3efb-45a9-8c69-a16936d0ab3d)
The screenshot it looks like in idep 1.1
![image](https://github.com/gexijin/idepGolem/assets/42040574/c94178f7-3ad5-46ae-9360-3f25c3e51bdf)

**Comment by gexijin** [comment]
Delete sorting by SD. This should solve this. 
Jenny, please double check.
