### ISSUE TITLE
Complete the report in Pre-Process tab

### ISSUE THREAD

**Issue by gexijin** [gexijin/idepGolem#538]
**Is your feature request related to a problem? What value do you see this adding? Please describe.**
The Report generated in the Pre-Process tab includes some but not all results. The QC plots are not included. 

**Describe the solution you'd like**
Add QC plot and the gene plot (as configured by the user, or default) to the report. 

**Additional context**
Note that QC plot is different depending on the type of data (read counts vs. normalized vs. FC+ FDR). It also varies depending on the genome annotation (Ensembl, STRING, unannotated). The STRING species has no genome annotation.

**Comment by ChrisTret** [comment]
Gene plot still needs to be added. Developers: Current error with Gene plot in preprocess RMD is "Error in if: argument is of length zero". I will keep looking for its source.

**Comment by gexijin** [comment]
Let's go without the gene plot for now.
