### ISSUE TITLE
color option for DEG and Pathway plots

### ISSUE THREAD

**Issue by JianYes** [gexijin/idepGolem#543]
**Is your feature request related to a problem? What value do you see this adding? Please describe.**
We have color option for heatmaps, Volcano, MA, and Scatter plot in DEG2, but no color option for 
![image](https://github.com/gexijin/idepGolem/assets/42040574/bd00aef8-4e2f-40ad-8898-189d5f156f4c)
![image](https://github.com/gexijin/idepGolem/assets/42040574/cd512e69-89aa-425b-835f-a4590292f4ef)

**Describe the solution you'd like**
Add color option for DEG1/Results, Pathway/PGSEA, PGSEA w/all samples

**Describe alternatives you've considered**

**Additional context**

**Comment by ChrisTret** [comment]
Could someone please clarify for me which plot is Pathway/PGSEA? I just made a pull request and now all Pathway plots other than Network have color options. Thank you so much as always!

**Comment by JianYes** [comment]
Chris, here attached is the example plot for Pathway/PGSEA. It's better to have color option. Same for Pathway/PGSEA w/all samples. Thanks!
![image](https://github.com/gexijin/idepGolem/assets/42040574/eaea7b1e-29d5-4bcd-a4d9-db7131c04071)
