### ISSUE TITLE
C stack error with R 4.2.3

### ISSUE THREAD

**Issue by EricTulowetzke** [gexijin/idepGolem#546]
**Describe the bug**
When using R.2.3 all figures will have a C stack error. This is not an error when using R 4.1.3

**Expected behavior**

**Screenshots**
R 4.2.3
<img width="961" alt="image" src="https://github.com/gexijin/idepGolem/assets/61069424/c2575c5d-68a3-4cce-9bc0-3d1d0743b161">

R 4.1.3
<img width="961" alt="image" src="https://github.com/gexijin/idepGolem/assets/61069424/7b269fdf-e620-4bae-9329-67023743257b">

**Comment by EricTulowetzke** [comment]
This same issue happens with R 4.3.1 

<img width="961" alt="image" src="https://github.com/gexijin/idepGolem/assets/61069424/34384db9-880d-4a0f-8857-2c0cb22b5624">

**Comment by gexijin** [comment]
This maybe specific to Apple M1? Unable to reproduce on my laptop.
