### ISSUE TITLE
Experiment Design fails to load

### ISSUE THREAD

**Issue by Moldenke1** [gexijin/idepGolem#547]
**Describe the bug**
At the "Load data" stage, "experiment design" fails to load any factors. If preprocess is then selected, IDEP crashes (see "Pre-porcess crash1/2).

**To Reproduce**
After completing initial steps 1-3,  load corresponding experiment design file.
2. Click on 'Step 4. Optional: experiment design' and load file.
3.. See error "Ignoring rows with one unique levels:" pops up twice (see attached "Missing step 3 and experiment design loading error"). In the study design window factors are listed with "No data available in table" below factors (see attached "Missing study design factors")

**Expected behavior**
Experiment design loads and factors are shown. Preprocess stage should not result in crash.

**Additional context**
1. I am running IDEP using Docker. 
2. When using last month (i.e. previous version/image) I did not have this problem. 
3. I tried replicating the issue using the online testing version, which appears to be running IDEP 1.11 and did not have this issue. 
4. I removed IDEP and reinstalled IDEP in docker, which did not resolve issue. 
5. I tried both .txt and .csv formats for the design file.
6. It may be unrelated, but step 3 is no longer present after loading expression data file (you can see this in the attached "Missing step 3 and experiment design loading error" screenshot.
<img width="1280" alt="Pre-process crash1" src="https://github.com/gexijin/idepGolem/assets/79023146/d1235445-9947-4d7d-a4ed-14b09362fce0">
<img width="1280" alt="Pre-process crash2" src="https://github.com/gexijin/idepGolem/assets/79023146/70e21f74-daf1-4143-98df-300c3899cf17">
<img width="1280" alt="Missing step 3 and experiment design loading error" src="https://github.com/gexijin/idepGolem/assets/79023146/bfe103c3-002f-4823-914c-a78e04f16ce9">
<img width="1280" alt="Missing study design factors" src="https://github.com/gexijin/idepGolem/assets/79023146/88d38e04-b900-4008-9637-9c6beb140338">

**Comment by Moldenke1** [comment]
In lieu to running iDEP through docker, I decided to download R and run iDEP locally. The above described issue does not occur when running iDEP as an R package.

**Comment by gexijin** [comment]
Thank you for the detailed report and update. As a small team, we rely on feedbacks like this to improve iDEP.
I haven't updated the image in a while. Will do that.

**Comment by Moldenke1** [comment]
No problem, happy to help and thanks for the software!

Yeah, i assumed resources are limited based on the website descriptions. I know issues like the one i was having can often be isolated and that any additional information can often clarify the issue and save alot of time.



On Sep 6, 2023, at 4:39 PM, Steven Ge ***@***.***> wrote:

﻿

Thank you for the detailed report and update. As a small team, we rely on feedbacks like this to improve iDEP.
I haven't updated the image in a while. Will do that.

**Comment by EricTulowetzke** [comment]
I will look at this will I look at #549
