### ISSUE TITLE
idep 1.1 will disconnect automatically if the data format is not acceptable

### ISSUE THREAD

**Issue by JianYes** [gexijin/idepGolem#549]
**Describe the bug**
For both data files list here, idep 1.1 will disconnect automatically because the data format is not acceptable.

**To Reproduce**
1. Go to 'idep 1.1'
2. Select species as it is: Human
3. Upload data file

**Expected behavior**
Give a message like "The data format is not acceptable. Please refer to https://idepsite.wordpress.com/data-format/ for more information"

**Screenshots**
![image](https://github.com/gexijin/idepGolem/assets/42040574/3869594b-38fb-4098-9c09-1fcc8938b2da)

**Additional context**
[Test_20230407.csv](https://github.com/gexijin/idepGolem/files/12470122/Test_20230407.csv)
[Gene Expression Matrix.csv](https://github.com/gexijin/idepGolem/files/12470121/Gene.Expression.Matrix.csv)

**Comment by malcook** [comment]
I am experiencing this error as well analyzing zebrafish GSE56176 GEO data from DEE2_Zebrafish and would love to use idep if it worked for me.

**Comment by malcook** [comment]
Thanks @EricTulowetzke , but I learned that the file I downloaded for GSE56176 GEO data from DEE2_Zebrafish  was empty, so the error is perhaps with  iDEP-READS, which I don't think should have created an empty file.

**Comment by JianYes** [comment]
@EricTulowetzke 
you may find the two files with unacceptable format in "Additional context", on the bottom of the issue #549. 
Thanks.


>
