### ISSUE TITLE
Data file can be uploaded in .96, but not in 1.1

### ISSUE THREAD

**Issue by JianYes** [gexijin/idepGolem#551]
**Describe the bug**
Data file "Zachary adjusted iDEP Input.csv" can be uploaded in .96, but not in 1.1

**To Reproduce**
1. Go to 'idep1.1'
2. Take the default Human as species for "Zachary.adjusted.iDEP.Input.csv" and mouse as species for "Adjusted_Gene Counts__Dr S__Idep analysis.csv"
3. Select expression data type
4. Upload the data file
5. See error

**Expected behavior**
The same data file should be loaded up by both .96 and 1.1

**Screenshots**
Same data file was uploaded in 0.96:
![image](https://github.com/gexijin/idepGolem/assets/42040574/8c19d539-5e09-4d67-8a92-a2f3de4ad7b1)
![image](https://github.com/gexijin/idepGolem/assets/42040574/236df6e5-0acf-4039-b900-4b023c9545c3)
Same data file could not be uploaded in 1.1:
![image](https://github.com/gexijin/idepGolem/assets/42040574/fa18e8b3-7172-4d8d-b67b-3941827fd3ae)
![image](https://github.com/gexijin/idepGolem/assets/42040574/96aa4457-f0aa-4dc3-9d5c-e976091ee970)

**Additional context**
[Zachary adjusted iDEP Input.csv](https://github.com/gexijin/idepGolem/files/12477894/Zachary.adjusted.iDEP.Input.csv)
[Adjusted_Gene Counts__Dr S__Idep analysis.csv](https://github.com/gexijin/idepGolem/files/12478006/Adjusted_Gene.Counts__Dr.S__Idep.analysis.csv)

**Comment by elenasendino** [comment]
Hi, did you manage to solve the problem? I am having the same issue since 2 weeks ago. I get the same popup message. I do not understand what is wrong. The demo data seems to load as normal but when I load my data file I get this error pop up message you show...

**Comment by EricTulowetzke** [comment]
I have opened a PR to fix this issue: #569. 

@elenasendino are any of your numbers in a format with double-quotes in them?

currently, IDEP 1.12 can't read files with numbers like this:

"1,123"

 I hope my code change will fix this issue but we have to wait and see.

**Comment by gexijin** [comment]
Fixed.
