### ISSUE TITLE
upload of data file with different file style

### ISSUE THREAD

**Issue by JianYes** [gexijin/idepGolem#552]
**Is your feature request related to a problem? What value do you see this adding? Please describe.**
Upload data file with different file styles may be easier for the users. idep even won't accept data file saved as csv but separated by semicolons.

**Describe the solution you'd like**
Can idep upload other different file styles, like csv separated with semicolons, XLS, XLSX?

**Additional context**
CSV data file separated by comma:
[GSE147134 col2.csv](https://github.com/gexijin/idepGolem/files/12477714/GSE147134.col2.csv)
CSV data file separated by semicolon:
[GSE147134 col2 (1).csv](https://github.com/gexijin/idepGolem/files/12477725/GSE147134.col2.1.csv)

**Comment by EricTulowetzke** [comment]
I will look at this will I look at #549

**Comment by gexijin** [comment]
Fixed. 
Please double check.
