### ISSUE TITLE
uploading of data file with multiple gene ID columns 

### ISSUE THREAD

**Issue by JianYes** [gexijin/idepGolem#553]
**Describe the bug**
Different situation in uploading of data file with multiple gene ID columns:
If the gene IDs are character IDs, such as Ensembl and symbol, idep1.1 will take only the first column of gene IDs. The system reads and analyzes the data file correctly.
If the gene IDs are numeric IDs, such as Entrez and NCBI gene ID, idep1.1 will take the gene ID column as read counts, using this column as part of the data matrix. The result will be messed up.

**To Reproduce**
1. Go to 'idep 1.1'
2. Select human as species for data file "processed_data (7).csv" and Mouse as species for data file "Oluwaseun_RNASeq Read count data-iDEP_with double gene column.csv"
3. Select "Normalized expression data" type for "processed_data (7).csv" and "Read counts data" type for  "Oluwaseun_RNASeq Read count data-iDEP_with double gene column.csv"
4. Upload the data file
5. See the results

**Expected behavior**
Is it possible for the system tell the IDs are IDs, even they are Entrez or NCBI gene ID?

**Screenshots**
Results of uploading "processed_data (7).csv":
![image](https://github.com/gexijin/idepGolem/assets/42040574/c1f0d7f6-f14d-45cb-941d-2fe1f32c72cb)
![image](https://github.com/gexijin/idepGolem/assets/42040574/c7dbbab7-0c87-4e3e-ae8c-a2c7f9941b81)
Results of uploading "Oluwaseun_RNASeq Read count data-iDEP_with double gene column.csv":
![image](https://github.com/gexijin/idepGolem/assets/42040574/9ed0ebed-72a1-4eae-80ac-89bd29921c00)
![image](https://github.com/gexijin/idepGolem/assets/42040574/67b544a3-3d67-4c4a-97e6-dcfd15bcef1e)

**Additional context**
[processed_data (7).csv](https://github.com/gexijin/idepGolem/files/12479814/processed_data.7.csv)
[Oluwaseun_RNASeq Read count data-iDEP_with double gene column.csv](https://github.com/gexijin/idepGolem/files/12479840/Oluwaseun_RNASeq.Read.count.data-iDEP_with.double.gene.column.csv)

**Comment by gexijin** [comment]
The double gene column file is not as shown on the screen shot. 
But anyway, this is nearly impossible without significant code change.
