### ISSUE TITLE
Count data file with comma cannot be read in

### ISSUE THREAD

**Issue by JianYes** [gexijin/idepGolem#554]
**Describe the bug**
Count data file with comma could not be read in. Did idep eat it?

**To Reproduce**
1. Go to 'idep 1.1'
2. Select Mouse as species for data file "RNASeq Read count data-iDEP.csv"
3. Select "Read counts data" type
4. Upload the data file
5. See the result, actually there is no result

**Expected behavior**
Can we delete the comma first for the uploaded data file then read in?

**Screenshots**
![image](https://github.com/gexijin/idepGolem/assets/42040574/971e2e3c-1c54-4fd1-ac4f-39d4ccd1cc59)

**Additional context**
[RNASeq Read count data-iDEP.csv](https://github.com/gexijin/idepGolem/files/12480164/RNASeq.Read.count.data-iDEP.csv)

**Comment by EricTulowetzke** [comment]
I will look at this will I look at #549

**Comment by EricTulowetzke** [comment]
the issue is when we have data like this "1,046" in the csv file I bet this is excel formatting issue I will find a work around since I have to deal with this issue at work too
