### ISSUE TITLE
Complete the report in Pathway tab

### ISSUE THREAD

**Issue by JianYes** [gexijin/idepGolem#566]
**Is your feature request related to a problem? What value do you see this adding? Please describe.**
“Generate Report” in Pathway tab only reports the parameters and tree only. Can we include in the other result too?

**Describe the solution you'd like**
The other result may include significant pathways, network, heatmap, and KEGG if it's available. 

**Describe alternatives you've considered**

**Additional context**

**Comment by gexijin** [comment]
Fixed.

**Comment by JianYes** [comment]
The download option is applied, but it get nothing with a note of "pathway-report htm  site wasn't available"

**Comment by gexijin** [comment]
Please double check. Close this if it is.

**Comment by JianYes** [comment]
When the download button is clicked, download processed. But like before, nothing was downloaded with a note of "pathway-report htm site wasn't available".

**Comment by gexijin** [comment]
Did you click the "Submit" button first? I tried and it works.
