### ISSUE TITLE
data file is acceptable by .96 but 1.1

### ISSUE THREAD

**Issue by JianYes** [gexijin/idepGolem#572]
**Describe the bug**
The data file attached is acceptable for 0.96 but wouldn't be accepted by 1.1. The system will automatically shut down when the file is being uploaded because there are empty lines in the data file. Idep keeps working if some cells for the same gene are missing, but not if there is no any data for certain gene.

**To Reproduce**
1. Go to 'iDEP1.11'
2. Click on 'Browse' and upload the file as attached
3. See error

**Expected behavior**
Edit the code asking idep to accept the data file with empty rows or cells. We may delete the rows without value first.

**Screenshots**

**Additional context**

[GSE37704_sailfish_genecounts_with_NA.csv](https://github.com/gexijin/idepGolem/files/12821621/GSE37704_sailfish_genecounts_with_NA.csv)

**Comment by gexijin** [comment]
Fixed
https://github.com/gexijin/idepGolem/commit/9a6b7261ddd0ac23fe3b5a102fec64745475b913
