### ISSUE TITLE
txt design file won't be recognized

### ISSUE THREAD

**Issue by JianYes** [gexijin/idepGolem#589]
**Describe the bug**
The csv or xlsx format design file will be uploaded successfully. But the txt format file won't be recognized.

**To Reproduce**
1. Go to 'iDEP 1.12'
2. Select Human as species
3. Upload the data file
4. Upload the design file in txt format
5. See error

**Expected behavior**
Make the system taking txt format design file as well.
**Screenshots**
![image](https://github.com/gexijin/idepGolem/assets/42040574/c0345cab-0294-4d2a-b943-4d1fce82bd95)

**Additional context**
[Hoxd1_knockdown_count_data.csv](https://github.com/gexijin/idepGolem/files/12934558/Hoxd1_knockdown_count_data.csv)
[Hoxd1_knockdown_count_data_one_factor_design_informatiom_in_txt.txt](https://github.com/gexijin/idepGolem/files/12934561/Hoxd1_knockdown_count_data_one_factor_design_informatiom_in_txt.txt)
There is no problem to upload csv design file:
[Hoxd1_knockdown_count_data_one_factor_design_informatiom.csv](https://github.com/gexijin/idepGolem/files/12934565/Hoxd1_knockdown_count_data_one_factor_design_informatiom.csv)

**Comment by jnkl31** [comment]
I get the same error message for all file formats...

**Comment by gexijin** [comment]
Probably fixed?

**Comment by JianYes** [comment]
I will check and let you know.

**Comment by JianYes** [comment]
Yes, it is fixed! :)
