### ISSUE TITLE
selection of PC number in x and y axis won't work in PCA 3D plot

### ISSUE THREAD

**Issue by JianYes** [gexijin/idepGolem#593]
**Describe the bug**
Selection of PC number in x and y axis won't work in PCA 3D plot, but works for z axis. For x and y axis, the PC numbers keep as 1 and 2 all the time. But for axis, the plot will change according to the selection of the PC number.

**To Reproduce**
1. Go to 'iDEP1.12'
2. Take default human species and load "2 groups; Human" demo data set
3. Submit and go to PCA 3D sub tab

**Expected behavior**
Is we change the PC number in x, y , and z axis, the plot should change according to the selection properly. 

**Screenshots**
![image](https://github.com/gexijin/idepGolem/assets/42040574/1d01685d-ec30-44ca-9e30-d06a9a5b3d47)

**Additional context**

**Comment by gexijin** [comment]
PCAx, PCAy are reused in the same module, causing this problem. @EricTulowetzke
Renamed to PCAx3d, PCAy3d, PCAz3d. Problem solved.
