### ISSUE TITLE
Geneset gmt file won't work for idep

### ISSUE THREAD

**Issue by JianYes** [gexijin/idepGolem#596]
**Is your feature request related to a problem? What value do you see this adding? Please describe.**
It's written in https://idepsite.wordpress.com/ that iDEP accepts 4 types of files, namely: Gene expression matrix, fold-change and P values, experimental design, and gene sets. Actually it won't take gene sets gmt file.

**Describe the solution you'd like**
Make gmt file acceptable too. 
If it's possible, add one gmt demo file to the demos, like normalized expression file and fold change file are suggested to add into the demos in issue #517.

**Comment by gexijin** [comment]
Fixed.
