### ISSUE TITLE
iDEP disconnects when selecting limma-voom or limma-trend methods for DEG1 tab with 2 Groups Demo Data

### ISSUE THREAD

**Issue by JianYes** [gexijin/idepGolem#601]
**Describe the bug**
When using the iDEP web application, I encounter a disconnection issue upon selecting either the limma-voom or limma-trend method within the DEG1 tab. This problem arises specifically when analyzing the provided 2 groups demo dataset. The application becomes unresponsive and loses connection, preventing further analysis. However, it works fine for other demo data files except 2 groups; Human, 2 groups; Mouse,  and Big data; Human if the both factors are selected.

**To Reproduce**
1. Load the 2 groups demo data in the iDEP interface.
2. Navigate to the DEG1 tab.
3. Select the method limma-voom or limma-trend and submit.
4. Observe that the application disconnects and becomes unresponsive.

**Expected behavior**
The application should perform the differential expression analysis using the selected method without disconnection or loss of responsiveness.

**Screenshots**
![image](https://github.com/gexijin/idepGolem/assets/42040574/9d6897a2-a771-4b3d-9feb-aab39bd26ec6)

**Comment by kamalmdmostafa** [comment]
I am encountering an issue with the Normalized data. Upon selecting the contrast pairs for comparison and hitting the submit button, the Shiny browser disconnects or closes.

**Comment by JianYes** [comment]
Would you please send an email to gelabinfo@gmail.com to explain the issue in detail? Thanks!

**Comment by gexijin** [comment]
I believed this is fixed. The reason is that when there are just two classes, limma returns results called logFC instead of log2FC.
