### ISSUE TITLE
Chang label for x-axis in DEG2/Volcano Plot as "Log2 Fold Change"

### ISSUE THREAD

**Issue by JianYes** [gexijin/idepGolem#620]
**Describe the bug**
The label for x-axis in DEG2/volcano plot should not be "Fold Change", but "Log2 Fold Change".

**To Reproduce**
1. Go to 'iDEP 1.1'.
2. Select species as Human and demo dataset "Human; 2 groups".
3. Upload data and hit submit in DEG1.
4. In DEG2 tab, select Volcano Plot subtab, the label for x-axis for the plot is "Fold Change" now, though it should be "Log2 Fold Change".

**Expected behavior**
Change the label for x-axis into "Log2 Fold Change" .

**Screenshots**
![image](https://github.com/gexijin/idepGolem/assets/42040574/876beb12-6961-4814-99b5-4d832d6bd035)

**Comment by ChrisTret** [comment]
Committed to my branch. Will pull when I push this afternoon.
