### ISSUE TITLE
Plot Error: Error: Insufficient values in manual scale. 24 needed but only 9 provided

### ISSUE THREAD

**Issue by rayhendricks** [gexijin/idepGolem#635]
**Describe the bug**
When the PCA section of iDEP 2.0 is run, there is a _Error: Insufficient values in manual scale. 24 needed but only 9 provided._ message that is displayed. Currently using bslib 0.40, as with bslib 0.61 the title bar is grayed out.  

**To Reproduce**
1. Open app and load data, we have 24 samples in our RNAseq experiment.
2. Click on PCA
3. See error

**Expected behavior**
I expect the PCA plot to appear.
**Screenshots**
![Screenshot from 2024-03-05 12-02-44](https://github.com/gexijin/idepGolem/assets/31388923/6389d34a-5cd1-420a-b559-eb13c2f6d775)

**Terminal**
`Warning: Error in palette: Insufficient values in manual scale. 24 needed but only 9 provided.
  127: <Anonymous>
  126: signalCondition
  125: signal_abort
  124: rlang::abort
  123: cli::cli_abort
  122: palette
  121: self$palette
  120: map
  119: self$map
  118: FUN
  117: lapply
  116: map_df
  115: scale$map_df
  114: FUN
  113: lapply
  111: map_df
  110: scales$map_df
  109: FUN
  108: lapply
  107: ggplotly_build
  106: gg2list
  105: ggplotly.ggplot
  103: ::
plotly
`

**Comment by gexijin** [comment]
Thank you for bringing this to our attention. This has been fixed.
