### ISSUE TITLE
Issue with Server 

### ISSUE THREAD

**Issue by Biomicrogen** [gexijin/idepGolem#637]
**Describe the bug**
When I attempt a DEG or preparing a html report for download, the server hangs and I get kicked out and need to start all over. I'm also not able to use 2.0 right now I keep getting an application unexpectedly exits error when the R packaged attempt to initiallize.

![idep error](https://github.com/gexijin/idepGolem/assets/10353433/5865535a-0ba8-437e-ba93-db4cae1da1f3)

**Comment by glucose888** [comment]
I also have the probrem, too. 

However, this issue "may be" solved by reloading the demo.

I'm not sure what the bug is. Anyway, it is work in my PC.

**Comment by gexijin** [comment]
Thanks for the feedback. Please provide us with more information so that we can reproduce the issue. If you want, you can email a part of your data to gelabinfo@gmail.com so that we could follow up. Thanks for using iDEP!

**Comment by gexijin** [comment]
We are optimizing the server settings. Will be upgrading the hardware soon. Thank you for your feedback.
